Kur 09 test ve java doc
eharuncan/e-kurban pull request #18
Opened 2023-01-06 18:36 UTC by bektasisik

2023-01-07 21:34 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/controller/HissedarController.java
> +    public ResponseEntity<HissedarDTO> addHissedar(@RequestBody @Valid HissedarCreateDTO hissedarCreateDTO) throws IllegalArgumentException {
method'un exception throw etmesine gerek yok. 
https://www.baeldung.com/java-exceptions
bu linki inceler misin @bektasisik

2023-01-07 21:35 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/domain/Hisse.java
> +            cascade = CascadeType.REMOVE,
Cascade.REMOVE olursa hisse silindiği zaman kurban da silinir, bu istediğimiz bir senaryo mu

2023-01-07 21:35 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/domain/Kurban.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Neden AUTO'dan IDENTITY'e çevirdik ?

2023-01-07 21:36 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/repository/HisseRepository.java
> +    void deleteHisse(@Param("id") Long id);
JPA içerisinde bulunan deleteById methodu kullanabilirz

2023-01-07 21:37 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/repository/LoadDbData.java
> +            //hisseRepository.save(hisse);
Gereksiz ise kaldıralım. Gerekli ise neden yoruma aldığımızı yazalım

2023-01-07 21:37 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/service/HisseService.java
> +        return hisseRepository.findById(id).orElseThrow(() -> new MissingFormatArgumentException("Hisse bulunamadı"));
Neden MissingFormatArgumentException kullanıyoruz ?

2023-01-07 21:39 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/service/HisseService.java
> +        Kurban kurban = kurbanService.getKurban(hisse.getKurban().getId());
hisse içerisinde zaten kurban entity'si var. Neden tekrar id'sini alıp repo'dan çekiyoruz.

`Hisse hisse = getHisseById(id);
 Kurban kurban = hisse.getKurban();
 hisseRepository.deleteHisse(id);
 kurbanService.updateDurum(kurban);`

2023-01-07 21:43 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/service/HissedarService.java
> +        // ayrı
Güncelleme işlemi için validasyon koyulmamış

2023-01-07 21:44 UTC, enesbahadir requested changes
Yorum yazdığım noktaları kontrol edebilir miyiz?

2023-01-08 20:33 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/domain/Hisse.java
> +            cascade = CascadeType.REMOVE,
![image](https://user-images.githubusercontent.com/50755139/211217708-11c9d751-de22-4e71-abea-8f98ec2ba5df.png)
cascade default oalrak bırakmak hiçbirini kullanmamak oldugu için cascade ' i kaldırdım

2023-01-08 20:34 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/controller/HissedarController.java
> +    public ResponseEntity<HissedarDTO> addHissedar(@RequestBody @Valid HissedarCreateDTO hissedarCreateDTO) throws IllegalArgumentException {
![image](https://user-images.githubusercontent.com/50755139/211217755-313451af-5c6c-4f67-90b5-721ab00692a9.png)

2023-01-08 20:36 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/domain/Kurban.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
tüm taboloların sequence ' i aynı sırada ilerliyordu,
mesela kurban eklemesi yapılınca kurbanId=1, hissedar ekleme yapılınca hissedarId=2 olarak devam ediyordu,
Identity vererek herbirirni 1 den başlattık

2023-01-08 20:37 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/repository/HisseRepository.java
> +    void deleteHisse(@Param("id") Long id);
![image](https://user-images.githubusercontent.com/50755139/211217885-1f762d04-f4e9-4911-b4ae-e02805833768.png)

2023-01-08 20:39 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/repository/LoadDbData.java
> +            //hisseRepository.save(hisse);
![image](https://user-images.githubusercontent.com/50755139/211217931-384b6056-abdf-41b0-b91f-fcf5d782a30b.png)
client'a mock data gitsin diye eklenmişti başta

2023-01-08 20:40 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/service/HisseService.java
> +        return hisseRepository.findById(id).orElseThrow(() -> new MissingFormatArgumentException("Hisse bulunamadı"));
kaldırdım abi

2023-01-08 20:41 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/controller/HissedarController.java
> +    public ResponseEntity<HissedarDTO> addHissedar(@RequestBody @Valid HissedarCreateDTO hissedarCreateDTO) throws IllegalArgumentException {
@bektasisik neden ekran görüntüsü kullanıyorsun, 
![image](https://user-images.githubusercontent.com/70328974/211217986-3110435d-0aa7-4256-af15-cff035a061a7.png)
bunu kullanarak değişiklik yaptığın kısımları yazabilrsin. Bu şekilde ekran görüntüsü aldığında okunması zor oluyor.

2023-01-08 20:43 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/service/HisseService.java
> +        Kurban kurban = kurbanService.getKurban(hisse.getKurban().getId());
![image](https://user-images.githubusercontent.com/50755139/211218140-3090459e-3986-4a01-b1b5-d7e30052b632.png)
teşekkürler abi gözümden kaçmış hiç öyle düşünmemiştim

2023-01-08 20:45 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/repository/HisseRepository.java
> +    void deleteHisse(@Param("id") Long id);
Ekran görüntüsü ile ne anlatmaya çalıştığını anlamadım @bektasisik hocam. Kullanıldığı yeri değiştirmişsin galiba ama bu şekilde sadece kod olan ekran görüntüsü atarak bulmaca gibi çözmem icab ediyor.
Basitçe method silindi yazsan yeterli olur.

2023-01-08 20:45 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/service/HissedarService.java
> +        // ayrı
![image](https://user-images.githubusercontent.com/50755139/211218224-1c29b46a-cfae-4cf1-b154-222bdf30fea2.png)
bunun kontrolunu yapacak bir senaryo mimarisi düşünemiyorum aklım almıyor göremiyorum

2023-01-08 20:46 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/repository/LoadDbData.java
> +            //hisseRepository.save(hisse);
Neden bu kod bloğu yorumda onu sormuştum aslında. Burada sildiğini mi anlamam gerekiyor

2023-01-08 20:59 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/domain/Hisse.java
> +            cascade = CascadeType.REMOVE,
`cascade = CascadeType.REMOVE` duruyor hocam

2023-01-08 21:04 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/domain/Hisse.java
> +            cascade = CascadeType.REMOVE,
düzelttim şimdi abi

2023-01-08 21:04 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/service/KurbanService.java
> +        return (kurban.getCins() == KurbanCins.BUYUKBAS && kurban.getHisseList().size() == kurban.getHisseAdedi()) || (kurban.getCins() == KurbanCins.KUCUKBAS && kurban.getHisseList().size() == kurba
`(a && b) || (c &&b)` şeklinde bir kontrol var `(a||c) && b` yapabilir miyiz ? Ayrıca kurbanın cinsi zaten ya büyükbaş ya küçükbaş olmuyor mu neden onu kontrol ediyoruz. direk olarak `kurban.getHisseList().size() == kurban.getHisseAdedi()` bu kontrol yeterli değil mi

2023-01-08 21:05 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/repository/HisseRepository.java
> +    void deleteHisse(@Param("id") Long id);
deleteHisse yerine JPA daki deleteById yi kullandım abi

2023-01-08 21:05 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/repository/LoadDbData.java
> +            //hisseRepository.save(hisse);
sildim abi yorumları

2023-01-08 21:06 UTC, enesbahadir approved these changes

2023-01-08 21:07 UTC, merged

2023-01-08 21:07 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/service/KurbanService.java
> +        return (kurban.getCins() == KurbanCins.BUYUKBAS && kurban.getHisseList().size() == kurban.getHisseAdedi()) || (kurban.getCins() == KurbanCins.KUCUKBAS && kurban.getHisseList().size() == kurba
küçükbaş ise hisseadedi 1 oluyor abi büyükbaş ise 7 `kurban.getHisseList().size() == kurban.getHisseAdedi()` yazdığımızda cinsine göre hisse adedini anlayabilir mi abi