Kur 02 kurban ekleme işlemi
eharuncan/e-kurban pull request #2
Opened 2022-12-26 16:47 UTC by bektasisik

kurban, hisse, hissedar domainleri oluşturuldu.
KurbanCreate.feature dosyasında testler yazıldı ve step definitions kısımları implement edildi

2022-12-27 07:41 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/controller/KurbanController.java
> +    public Kurban addKurban(@RequestBody  KurbanCreateDTO kurbanCreateDTO){
Burada neden Entity sınıfı kullanıyoruz ? Domain katmanını izole etmek için ne yapabiliriz ?

2022-12-27 07:41 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/domain/Hisse.java
> +    @Id
javadoc ekler misin  ?

2022-12-27 07:41 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/domain/Hissedar.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
javadoc ekler misin ?

2022-12-27 07:42 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/domain/Kurban.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
javadoc ekler misin ?

2022-12-27 07:46 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/service/KurbanService.java
> +    }
Kesim sırasını bu şekilde arttırmak concurrent isteklerde sorun çıkaraktır. Tek bir kullanıcı ile bu sistemin çalıştırılması halinde ise bazı problemlere sebep olabilir;

- Telef olan kurban yerine aynı sırada kurban eklenenemesi 
- Kullanıcının sırayı yanlış girmesi durumunda düzenleme yaptığında boş sıra kalaması gibi 

Bu riskleri kabul ediyorsanız bu şekilde yapabilirsiniz. @bektasisik @abmehmet

2022-12-27 07:46 UTC, enesbahadir commented on server/src/test/java/com/aurora/ekurban/bdd/steps/KurbanCreateStepDefinitions.java
> +        Assert.assertEquals(HttpStatus.FORBIDDEN.value(), result.andReturn().getResponse().getStatus());
Başarısız senaryoda dönüş değeri FORBIDDEN 403 olmamalıdır, düzeltebilir misin ?

2022-12-27 07:48 UTC, enesbahadir requested changes
.idea dosyasını gitignore dosyasıan ekler misiniz ?

2022-12-27 08:09 UTC, bektasisik commented on server/src/test/java/com/aurora/ekurban/bdd/steps/KurbanCreateStepDefinitions.java
> +        Assert.assertEquals(HttpStatus.FORBIDDEN.value(), result.andReturn().getResponse().getStatus());
@Then("Ekleme işlemi başarısız olur")
    public void eklemeIslemiBasarisizOlur() {
        ResultActions result = (ResultActions) scenerioContext.getContext("result");
        Assert.assertEquals(HttpStatus.BAD_REQUEST.value(), result.andReturn().getResponse().getStatus());
    }

2022-12-27 08:09 UTC, bektasisik commented on server/src/main/java/com/aurora/ekurban/controller/KurbanController.java
> +    public Kurban addKurban(@RequestBody  KurbanCreateDTO kurbanCreateDTO){
@PostMapping(value = "kurban")
    public ResponseEntity<Kurban> addKurban(@RequestBody @Valid KurbanCreateDTO kurbanCreateDTO) {
        return new ResponseEntity<>(kurbanService.addKurban(kurbanCreateDTO), HttpStatus.CREATED);
    }

2022-12-27 08:33 UTC, abmehmet commented on server/src/test/java/com/aurora/ekurban/bdd/steps/KurbanCreateStepDefinitions.java
> +        Assert.assertEquals(HttpStatus.FORBIDDEN.value(), result.andReturn().getResponse().getStatus());
```
@then("Ekleme işlemi başarısız olur")
public void eklemeIslemiBasarisizOlur() {
ResultActions result = (ResultActions) scenerioContext.getContext("result");
Assert.assertEquals(HttpStatus.BAD_REQUEST.value(), result.andReturn().getResponse().getStatus());
}
```

2022-12-27 11:39 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/controller/KurbanController.java
> +    public Kurban addKurban(@RequestBody  KurbanCreateDTO kurbanCreateDTO){
Methodun dönüş değeri entity sınıfının kendisi olursa domain katmanını izole etmiş olamayız

2022-12-28 07:55 UTC, enesbahadir commented on server/src/main/java/com/aurora/ekurban/service/KurbanService.java
> +        });
Entity'den DTO'ya dönüşümü sağlayan bir method yazılırsa kod tekrarı yapılmamış olur

2022-12-28 07:57 UTC, enesbahadir approved these changes

2022-12-28 07:57 UTC, merged